### PR TITLE
Hemalurgy and Feruchemy rendering redesign.

### PR DESCRIPTION
**Pull request by AngelOfCreation**
## Changes proposed in this pull request:
Added 6 more bind points around the players rib cage to match canonical bind points.

### CODE REVIEW

**Review by leafreynolds — CHANGES_REQUESTED** [review]
image

Looks great :)

While you are in the area, can you move the linchpin spike from being bound to the head, and instead is at the top of the torso above the back spike?

**Comment by AngelOfCreation** [comment]
> image
> 
> Looks great :)
> 
> While you are in the area, can you move the linchpin spike from being bound to the head, and instead is at the top of the torso above the back spike?

I can try. It's getting pretty late tonight where I am, and I've been working for several hours on smoothing out the spikes so they don't jut out as much. I also added a third arm spike/bracelet slot, smoothing them out as well as the hand spike, plus a 2nd back slot as shown [here](https://coppermind.net/w/images/Hemalurgy_table.jpg). What do you think?
image
I'll try and work on the linch pin tomorrow.

**Comment by leafreynolds** [comment]
no rush at all, next curseforge update wont be for another week or two at the minimum, but also may be longer

**Comment by AngelOfCreation** [comment]
> no rush at all, next curseforge update wont be for another week or two at the minimum, but also may be longer

Will this work, or do you want it slightly lower? As it is right now, the head obstructs the view of it when you tilt your head back.
image
image

**Comment by leafreynolds** [comment]
> Will this work, or do you want it slightly lower? As it is right now, the head obstructs the view of it when you tilt your head back.

Let's put it a little lower so it's less covered when the head is tilted back, but otherwise looks good :)

**Comment by AngelOfCreation** [comment]
> > Will this work, or do you want it slightly lower? As it is right now, the head obstructs the view of it when you tilt your head back.
> 
> Let's put it a little lower so it's less covered when the head is tilted back, but otherwise looks good :)

How about this? I also added a secondary cube to the back of the eye spikes and shrunk them down. Front is the same size, but flatter against the face like the rib spikes. It's hard to tell in third person though.
image

**Comment by leafreynolds** [comment]
> How about this? I also added a secondary cube to the back of the eye spikes and shrunk them down. Front is the same size, but flatter against the face like the rib spikes. It's hard to tell in third person though.

I'd prefer to keep the eye spikes the same size, as 2x2 pixels will cover eyes in most player skins (like mine), other wise it looks real weird.

Otherwise, looking good. Did you add an extra back spike to match the hemalurgy poster?

**Comment by leafreynolds** [comment]
disregard last comment, clarification was provided in discord

**Comment by X66Herobrine66X** [comment]
> > How about this? I also added a secondary cube to the back of the eye spikes and shrunk them down. Front is the same size, but flatter against the face like the rib spikes. It's hard to tell in third person though.
> 
> I'd prefer to keep the eye spikes the same size, as 2x2 pixels will cover eyes in most player skins (like mine), other wise it looks real weird.
> 
> Otherwise, looking good. Did you add an extra back spike to match the hemalurgy poster?
The front of the eye spikes remains 2x2, see my comment in discord. And yea I added a second back slot.

**Comment by AngelOfCreation** [comment]
I've got an update for you on my progress. I've extended the back spikes by 2 more to better match [this](https://media.discordapp.net/attachments/837601788755836948/1170196898183921684/Inquisitor.png?ex=655829c9&is=6545b4c9&hm=203ff838c016d0c7a9231a6dfe53917c2638808cc482ccdf17053d776e68c713&=&width=375&height=603) image. I've split certain sections into the following categories so we can whitelist only certain spike types:
- Upper Ribs
- Upper Middle Ribs
- Lower Middle Ribs
- Lower Ribs
- Hands
- Shoulder Sides
- Shoulder Tops
- Eyes
- Linchpin
- Back (May split this one up into 4 rows of 1, like ribs)
Each category has its own separate json file for whitelisting. I also plan on adding two chest spikes, also to match [this](https://media.discordapp.net/attachments/837601788755836948/1170196898183921684/Inquisitor.png?ex=655829c9&is=6545b4c9&hm=203ff838c016d0c7a9231a6dfe53917c2638808cc482ccdf17053d776e68c713&=&width=375&height=603) image. Additionally, I've given spike slots their own cutout texture. Unfortunately, animating the bracelet/spike dual slots to flash between spike and bracelet cutouts is probably beyond my expertise, so I've left them as bracelet cutouts for now.
image
image
image

**Review by leafreynolds — APPROVED** [review]

**Pull request merged**
