### PR TITLE
Feruchemy Descriptions

### PR DESCRIPTION
**Pull request by Luke13234**
Most of the Feruchemy Descriptions and a couple fixes to Allomancy Descriptions.

### CODE REVIEW

**Review by leafreynolds — COMMENTED** [review]
Lerasium hemalurgy section is missing a `break;` 
image

**Review by leafreynolds — CHANGES_REQUESTED** [review]
Lerasium section missing `break;`

**Comment by Luke13234** [comment]
Happy Now?

**Review by leafreynolds — APPROVED** [review]
Looks great :) thanks~

**Pull request merged**
